### ISSUE TITLE
Doesn't work in latest nightly anymore

### ISSUE THREAD

**Issue by mohtar** [mhallin/murmurhash3-rs#2]
I had to change the crate attributes to the following:

```
#![feature(hashmap_hasher)]
#![feature(vec_push_all)]
```

So that the library would compile again.

My `rustc --version` output is `rustc 1.3.0-nightly (8fa2185e0 2015-06-27)`

**Comment by mhallin** [comment]
This should be resolved by the 0.0.5 release.
